#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

# ARGV = [add, Tech]
command = ARGV[0]
portfolio_name = ARGV[1]

params = { command: command, portfolio: { name: portfolio_name } }
portfolio_controller = PortfolioController.new(params)

if command == "add"
  portfolio_controller.create
elsif command == "list"
  portfolio_controller.index
elsif command == "remove"
  portfolio_controller.destroy
elsif command == "edit"
  ticker_controller = TickerController.new(params)
  ticker_controller.edit
elsif command == "view"
  ticker_controller = TickerController.new(params)
  ticker_controller.view
else
  unless command == "help"
    puts "RubyStocks does not support the '#{command}' command.\n\n"
  end
  puts <<EOS
Currently supported commands are:
* list (to view names of all portfolios)
* add <portfolio_name>
* remove <portfolio_name>
* view <portfolio_name>
* edit <portfolio_name>

See the README for more details

EOS
end
